### ISSUE TITLE
Skip the unmapped changes section if empty

### ISSUE THREAD

**Issue by dylanratcliffe** [overmindtech/ovm-cli#128]
If there aren't any unmapped changes, just skip the whole section:

<img width="1023" alt="Screenshot 2023-11-30 at 10 00 26 am" src="https://github.com/overmindtech/ovm-cli/assets/8799341/4f7cd1e0-1b70-4efc-8750-0311cbe98e5c">

**Comment by DavidS-ovm** [comment]
Implemented in https://github.com/overmindtech/ovm-cli/pull/138
